name: Status
version: '${project.version}'
main: de.weihnachtsmannyt.status.Status
api-version: 1.21
authors: [ WeihnachtsmannYT ]
description: Status Plugin
depend: [ CustomInventoryUI ]
commands:
  status: