name: Status
version: '1.2.7-RELEASE'
main: de.weihnachtsmannyt.status.Status
api-version: 1.21
authors: [ WeihnachtsmannYT ]
description: Status Plugin
depend: [CustomInventoryUI]
commands:
  status: