name: StatusGui
version: '${project.version}'
main: de.weihnachtsmannyt.statusgui.Statusgui
api-version: 1.21
authors: [ WeihnachtsmannYT ]
description: Gui for Statuts pl
depend: [ Status ]
commands:
  statusgui:
    description: Opens Gui for Status
