name: CustomInventoryUI
version: '${project.version}'
main: de.weihnachtsmannyt.custominventoryui.CustomInventoryUI
api-version: '1.21'
load: STARTUP
authors: [ Weihnachtsmannyt ]
description: CustomInventoryUI
commands:
  openui: