name: AfkApi
version: '${project.version}'
main: de.weihnachtsmannyt.afkapi.AfkApi
api-version: 1.20
authors: [ WeihnachtsmannYT ]
description: Detects Afk Players
depend: [ Status ]
commands:
  isafk:
    description: Check to see if you or someone else is AFK
  afk:
    description: Toggle your AFK status